name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on making your first issue!'
        pr-message: 'Congratulations on making your first pull request! If this pull request is a change to one of my mods, make sure things work first!'
